spring:
  application:
    name: gympass
  profiles:
    active: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}